version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:${REDIS_PORT}"
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:${POSTGRES_PORT}"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
