"""Init

Revision ID: 77652c0b7ff5
Revises: 3fbdeb9d01e4
Create Date: 2024-01-31 15:02:55.525238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77652c0b7ff5'
down_revision: Union[str, None] = '3fbdeb9d01e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
