"""Init

Revision ID: bd9dae2eb5f4
Revises: 2d34556c98d5
Create Date: 2024-01-31 19:56:59.253260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd9dae2eb5f4'
down_revision: Union[str, None] = '2d34556c98d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'done')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('done', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
